function report = validate_battery(result)
p=result.parameters; w=result.waveforms;
positive=w.command_power_w>0; negative=w.command_power_w<0;
report.metrics=struct( ...
    'initial_soc',w.soc(1),'final_soc',w.soc(end), ...
    'minimum_voltage_v',min(w.terminal_voltage_v), ...
    'maximum_voltage_v',max(w.terminal_voltage_v), ...
    'maximum_discharge_current_a',max(w.current_a), ...
    'maximum_charge_current_a',abs(min(w.current_a)), ...
    'maximum_temperature_c',max(w.temperature_c), ...
    'discharge_power_error_w',max(abs(w.terminal_power_w(positive)-w.command_power_w(positive))), ...
    'charge_power_error_w',max(abs(w.terminal_power_w(negative)-w.command_power_w(negative))), ...
    'energy_residual_peak_j',max(abs(w.energy_residual_j)), ...
    'chemical_energy_throughput_j',sum(abs(diff(w.chemical_energy_j))));
m=report.metrics;
report.checks=struct( ...
    'finite',all(isfinite(w{:,:}),'all'), ...
    'soc_bounds',min(w.soc)>=p.minimum_soc && max(w.soc)<=p.maximum_soc, ...
    'voltage_bounds',m.minimum_voltage_v>=p.minimum_terminal_voltage_v ...
        && m.maximum_voltage_v<=p.maximum_terminal_voltage_v, ...
    'discharge_current',m.maximum_discharge_current_a<=p.maximum_discharge_current_a, ...
    'charge_current',m.maximum_charge_current_a<=p.maximum_charge_current_a, ...
    'thermal',m.maximum_temperature_c<45, ...
    'bidirectional',any(positive)&&any(negative), ...
    'power_tracking',m.discharge_power_error_w<1e-6 && m.charge_power_error_w<1e-6, ...
    'energy_conservation',m.energy_residual_peak_j/max(1,m.chemical_energy_throughput_j)<1e-4, ...
    'soc_direction',w.soc(find(w.time_s>=600,1))<w.soc(find(w.time_s>=300,1)) ...
        && w.soc(find(w.time_s>=900,1))>w.soc(find(w.time_s>=600,1)));
report.passed=all(structfun(@logical,report.checks));
end
