function build_sogi_pll_model()
%% Build a discrete SOGI-PLL and repeatable disturbed-grid test source.
script_dir=fileparts(mfilename('fullpath'));
cd(script_dir);
pll_params;
model_name='sogi_pll_validation';

if bdIsLoaded(model_name); close_system(model_name,0); end
if exist([model_name '.slx'],'file'); delete([model_name '.slx']); end
new_system(model_name);
set_param(model_name,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','T_pll','StopTime','T_pll_sim','ReturnWorkspaceOutputs','on');

add_block('simulink/Sources/Clock',[model_name '/Time'],'Position',[45 85 75 105]);

source=[model_name '/Disturbed Grid Source'];
add_block('simulink/User-Defined Functions/MATLAB Function',source,'Position',[145 45 350 145]);
rt=sfroot; chart=rt.find('-isa','Stateflow.EMChart','Path',source);
chart.Script=sprintf([ ...
    'function [v_grid,theta_actual,f_actual] = grid_source(t)\n' ...
    'f0=%.17g; f1=%.17g; ts=%.17g; tj=%.17g; jump=%.17g;\n' ...
    'if t < ts; f_actual=f0; theta=2*pi*f0*t; else; f_actual=f1; theta=2*pi*f0*ts+2*pi*f1*(t-ts); end\n' ...
    'if t >= tj; theta=theta+jump; end\n' ...
    'if t >= %.17g && t < %.17g; envelope=%.17g; else; envelope=1; end\n' ...
    'v_grid=%.17g*envelope*(sin(theta)+%.17g*sin(5*theta)+%.17g*sin(7*theta)+%.17g*sin(2*pi*1300*t));\n' ...
    'theta_actual=mod(theta,2*pi);\n' ...
    'end\n'],f_pll_nom,f_pll_step,t_freq_step,t_phase_jump,phase_jump_rad, ...
    t_sag_start,t_sag_end,sag_pu,V_pll_pk,h5_pu,h7_pu,noise_pu);

pll=[model_name '/SOGI PLL'];
add_block('simulink/User-Defined Functions/MATLAB Function',pll,'Position',[455 35 680 165]);
chart=rt.find('-isa','Stateflow.EMChart','Path',pll);
chart.Script=sprintf([ ...
    'function [theta_est,f_est,v_alpha,v_beta,v_q,amplitude] = sogi_pll(v_grid)\n' ...
    '%%#codegen\n' ...
    'persistent va vb theta omega integ\n' ...
    'if isempty(va); va=0; vb=0; theta=0; omega=2*pi*%.17g; integ=0; end\n' ...
    'Ts=%.17g; k=%.17g; kp=%.17g; ki=%.17g; wmin=2*pi*%.17g; wmax=2*pi*%.17g;\n' ...
    'dva1=k*omega*(v_grid-va)-omega*vb; dvb1=omega*va;\n' ...
    'va_p=va+Ts*dva1; vb_p=vb+Ts*dvb1;\n' ...
    'dva2=k*omega*(v_grid-va_p)-omega*vb_p; dvb2=omega*va_p;\n' ...
    'va=va+0.5*Ts*(dva1+dva2); vb=vb+0.5*Ts*(dvb1+dvb2);\n' ...
    'amplitude=sqrt(va*va+vb*vb); norm_amp=max(amplitude,0.1*%.17g);\n' ...
    'vq=(va*cos(theta)+vb*sin(theta))/norm_amp;\n' ...
    'unsat=2*pi*%.17g+kp*vq+integ; omega=min(max(unsat,wmin),wmax);\n' ...
    'if (unsat==omega) || (unsat>wmax && vq<0) || (unsat<wmin && vq>0); integ=integ+Ts*ki*vq; end\n' ...
    'theta=mod(theta+Ts*omega,2*pi);\n' ...
    'theta_est=theta; f_est=omega/(2*pi); v_alpha=va; v_beta=vb; v_q=vq;\n' ...
    'end\n'],f_pll_nom,T_pll,k_sogi,Kp_pll,Ki_pll,f_pll_min,f_pll_max,V_pll_pk,f_pll_nom);

names={'v_grid','theta_actual','f_actual','theta_est','f_est','v_alpha','v_beta','v_q','amplitude'};
pos=[730 15;730 50;730 85;730 120;730 155;850 15;850 50;850 85;850 120];
for k=1:numel(names)
    add_block('simulink/Sinks/To Workspace',[model_name '/log_' names{k}], ...
        'VariableName',names{k},'SaveFormat','Timeseries', ...
        'Position',[pos(k,1) pos(k,2) pos(k,1)+85 pos(k,2)+25]);
end

add_line(model_name,'Time/1','Disturbed Grid Source/1');
add_line(model_name,'Disturbed Grid Source/1','SOGI PLL/1');
add_line(model_name,'Disturbed Grid Source/1','log_v_grid/1');
add_line(model_name,'Disturbed Grid Source/2','log_theta_actual/1');
add_line(model_name,'Disturbed Grid Source/3','log_f_actual/1');
for port=1:6
    target=names{port+3};
    add_line(model_name,sprintf('SOGI PLL/%d',port),['log_' target '/1']);
end

Simulink.BlockDiagram.arrangeSystem(model_name);
save_system(model_name);
fprintf('Model saved: %s.slx\n',model_name);
end
