#!/usr/bin/env python3
"""Validate analog ranges and generate matching C2000 scaling constants."""

import csv
import json
import math
import pathlib


ROOT = pathlib.Path(__file__).resolve().parent


def load_inputs():
    with (ROOT / "sensing_inputs.json").open(encoding="utf-8") as handle:
        return json.load(handle)


def calculate(data):
    full_scale_count = (1 << data["adc_bits"]) - 1
    adc_lsb_v = data["adc_reference_v"] / full_scale_count
    rows = []
    for channel in data["channels"]:
        adc_at_min = (channel["adc_offset_v"]
                      + channel["adc_gain_v_per_unit"] * channel["plant_min"])
        adc_at_max = (channel["adc_offset_v"]
                      + channel["adc_gain_v_per_unit"] * channel["plant_max"])
        rows.append({
            **channel,
            "adc_at_min_v": adc_at_min,
            "adc_at_max_v": adc_at_max,
            "low_headroom_v": adc_at_min,
            "high_headroom_v": data["adc_reference_v"] - adc_at_max,
            "plant_units_per_count": adc_lsb_v / channel["adc_gain_v_per_unit"],
            "counts_per_plant_unit": channel["adc_gain_v_per_unit"] / adc_lsb_v,
            "zero_count": channel["adc_offset_v"] / adc_lsb_v,
        })
    rc = data["anti_alias_resistance_ohm"] * data["anti_alias_capacitance_f"]
    sensor = data["current_sensor"]
    sensor_losses = {
        name: current * current * sensor["conductor_resistance_ohm"]
        for name, current in sensor["design_rms_current_a"].items()
    }
    return {
        "adc_full_scale_count": full_scale_count,
        "adc_lsb_v": adc_lsb_v,
        "anti_alias_cutoff_hz": 1.0 / (2.0 * math.pi * rc),
        "anti_alias_time_constant_s": rc,
        "current_sensor": {
            **sensor,
            "voc_setting_v": (sensor["overcurrent_threshold_a"]
                              * sensor["voc_scale_v_per_a"]),
            "conductor_loss_w": sensor_losses,
            "maximum_conductor_loss_w": max(sensor_losses.values()),
        },
        "channels": rows,
    }


def c_identifier(name):
    return "MG_ADC_" + name.upper()


def write_outputs(data, result):
    output_dir = ROOT / "results"
    output_dir.mkdir(exist_ok=True)
    csv_fields = [
        "name", "unit", "plant_min", "plant_max", "adc_at_min_v",
        "adc_at_max_v", "low_headroom_v", "high_headroom_v",
        "plant_units_per_count", "counts_per_plant_unit", "zero_count",
        "implementation",
    ]
    with (output_dir / "sensing_channels.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=csv_fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(result["channels"])
    with (output_dir / "sensing_metrics.json").open("w", encoding="utf-8") as handle:
        json.dump(result, handle, indent=2)
        handle.write("\n")

    generated = ROOT.parent / "firmware" / "c2000_port" / "generated"
    generated.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Generated by hardware/calculate_sensing.py. Do not hand edit. */",
        "#ifndef MICROGRID_ADC_SCALING_H",
        "#define MICROGRID_ADC_SCALING_H",
        "",
        f"#define MG_ADC_REFERENCE_V ({data['adc_reference_v']:.9g}f)",
        f"#define MG_ADC_FULL_SCALE_COUNT ({result['adc_full_scale_count']}.0f)",
        "",
    ]
    for row in result["channels"]:
        prefix = c_identifier(row["name"])
        lines.extend([
            f"#define {prefix}_ZERO_COUNT ({row['zero_count']:.9g}f)",
            f"#define {prefix}_UNITS_PER_COUNT ({row['plant_units_per_count']:.9g}f)",
        ])
    lines.extend(["", "#endif", ""])
    (generated / "adc_scaling.h").write_text("\n".join(lines), encoding="utf-8")

    channel_lines = []
    for row in result["channels"]:
        channel_lines.append(
            f"| {row['name']} | {row['plant_min']:.1f} to {row['plant_max']:.1f} {row['unit']} "
            f"| {row['adc_at_min_v']:.3f} to {row['adc_at_max_v']:.3f} V "
            f"| {row['plant_units_per_count']:.5f} {row['unit']}/count "
            f"| {min(row['low_headroom_v'], row['high_headroom_v']):.3f} V |"
        )
    report = f"""# Analog Measurement Design

Generated from `hardware/sensing_inputs.json`.

The {data['adc_bits']}-bit, {data['adc_reference_v']:.1f} V conversion is
{result['adc_lsb_v']*1000:.4f} mV/count. A {data['anti_alias_resistance_ohm']:.0f}
ohm and {data['anti_alias_capacitance_f']*1e9:.1f} nF output filter has a
{result['anti_alias_cutoff_hz']/1000:.2f} kHz cutoff and
{result['anti_alias_time_constant_s']*1e6:.2f} microsecond time constant.

| Channel | Required plant range | ADC range | Nominal resolution | Minimum rail headroom |
|---|---:|---:|---:|---:|
{chr(10).join(channel_lines)}

## Current sensor implementation

U6-U8 use the TI {result['current_sensor']['part_number']} 3.3 V, 50 mV/A
variant. Its specified linear range is +/-{result['current_sensor']['linear_range_a']:.0f} A.
Set VOC to {result['current_sensor']['voc_setting_v']:.3f} V for the
{result['current_sensor']['overcurrent_threshold_a']:.1f} A hardware threshold;
the specified maximum sensor response is
{result['current_sensor']['overcurrent_response_max_s']*1e9:.0f} ns.

At the design RMS currents, estimated internal-conductor loss is
{result['current_sensor']['conductor_loss_w']['pv_current']:.3f} W in the PV sensor,
{result['current_sensor']['conductor_loss_w']['dc_inductor_current']:.3f} W in the DC-inductor sensor,
and {result['current_sensor']['conductor_loss_w']['grid_current']:.3f} W in the grid sensor.

## Calibration and validation

1. Keep PWM disabled and record at least 4096 samples for every zero or known
   reference condition. Store mean offset and noise RMS.
2. Apply two traceable calibration points spanning at least 70% of each channel
   range. Store gain and offset with a version and CRC in nonvolatile memory.
3. Reject readings outside the required plant range plus 5% tolerance and fault
   any channel that remains unchanged across the stale-sample limit.
4. Compare software overcurrent thresholds against sensor ALERT and external
   comparator thresholds. The external path must trip all PWM channels without
   CPU execution.
5. Verify phase delay of grid-voltage and grid-current paths together because
   unmatched delay creates active/reactive power error.

The generated header `firmware/c2000_port/generated/adc_scaling.h` provides
nominal commissioning constants. Stored calibration values supersede these
nominal constants during operation.
"""
    (output_dir / "sensing_report.md").write_text(report, encoding="utf-8")


def main():
    data = load_inputs()
    result = calculate(data)
    write_outputs(data, result)
    print(f"Validated {len(result['channels'])} analog channels")
    print(f"Anti-alias cutoff: {result['anti_alias_cutoff_hz']/1000:.2f} kHz")


if __name__ == "__main__":
    main()
