function report = validate_microgrid_transition(result)
p=result.parameters; w=result.waveforms;
island_1=w.time_s>=0.55 & w.time_s<0.68;
island_2=w.time_s>=0.84 & w.time_s<0.98;
if isfinite(result.reconnect_time_s)
    after_reconnect=w.time_s>=result.reconnect_time_s+0.06 & w.time_s<result.reconnect_time_s+0.16;
    reconnect_window=w.time_s>=result.reconnect_time_s & w.time_s<result.reconnect_time_s+0.04;
    reconnect_peak=max(w.grid_current_rms_a(reconnect_window));
    post_reconnect_voltage=mean(w.bus_voltage_rms_v(after_reconnect));
else
    reconnect_peak=inf;
    post_reconnect_voltage=nan;
end
share_p_1=mean(w.power_1_w(island_1)./(w.power_1_w(island_1)+w.power_2_w(island_1)));
share_p_2=mean(w.power_1_w(island_2)./(w.power_1_w(island_2)+w.power_2_w(island_2)));
share_q_2=mean(w.reactive_1_var(island_2)./(w.reactive_1_var(island_2)+w.reactive_2_var(island_2)));
report.metrics=struct( ...
    'detection_delay_s',result.island_detection_time_s-p.grid_loss_time_s, ...
    'reconnect_time_s',result.reconnect_time_s, ...
    'pre_step_active_share_1',share_p_1, ...
    'post_step_active_share_1',share_p_2, ...
    'post_step_reactive_share_1',share_q_2, ...
    'island_voltage_min_v',min(w.bus_voltage_rms_v(island_1|island_2)), ...
    'island_voltage_max_v',max(w.bus_voltage_rms_v(island_1|island_2)), ...
    'island_frequency_min_hz',min([w.frequency_1_hz(island_1|island_2);w.frequency_2_hz(island_1|island_2)]), ...
    'island_frequency_max_hz',max([w.frequency_1_hz(island_1|island_2);w.frequency_2_hz(island_1|island_2)]), ...
    'reconnect_grid_current_peak_rms_a',reconnect_peak, ...
    'post_reconnect_voltage_mean_v',post_reconnect_voltage);
m=report.metrics;
report.checks=struct( ...
    'finite',all(isfinite(w{:,:}),'all'), ...
    'island_detected',isfinite(result.island_detection_time_s), ...
    'detection_under_two_cycles',m.detection_delay_s<=2/p.nominal_frequency_hz, ...
    'reconnected',isfinite(result.reconnect_time_s) && result.reconnect_time_s>p.grid_return_time_s, ...
    'active_share_pre_step',abs(m.pre_step_active_share_1-0.60)<0.03, ...
    'active_share_post_step',abs(m.post_step_active_share_1-0.60)<0.03, ...
    'reactive_share_post_step',abs(m.post_step_reactive_share_1-0.60)<0.06, ...
    'island_voltage',m.island_voltage_min_v>0.85*p.nominal_voltage_rms_v ...
        && m.island_voltage_max_v<1.10*p.nominal_voltage_rms_v, ...
    'island_frequency',m.island_frequency_min_hz>=49.0 ...
        && m.island_frequency_max_hz<=51.0, ...
    'source_current_limits',max(w.current_1_rms_a)<p.maximum_source_current_rms_a(1) ...
        && max(w.current_2_rms_a)<p.maximum_source_current_rms_a(2), ...
    'reconnect_current',m.reconnect_grid_current_peak_rms_a<p.maximum_reconnect_grid_current_rms_a, ...
    'post_reconnect_voltage',abs(m.post_reconnect_voltage_mean_v-p.nominal_voltage_rms_v)<0.03*p.nominal_voltage_rms_v);
report.passed=all(structfun(@logical,report.checks));
end
