function build_lcl_grid_model()
%% Build switching-level LCL filter and configurable low-voltage grid model.

script_dir = fileparts(mfilename('fullpath'));
cd(script_dir);
grid_tie_params;
model_name = 'hbridge_lcl_grid_open_loop';

if bdIsLoaded(model_name); close_system(model_name,0); end
if exist([model_name '.slx'],'file'); delete([model_name '.slx']); end

new_system(model_name);
set_param(model_name,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','T_step_grid','StopTime','T_sim_grid','ReturnWorkspaceOutputs','on');

% Synchronized references and test excitation.
add_block('simulink/Sources/Sine Wave',[model_name '/Grid Voltage'], ...
    'Amplitude','V_grid_pk','Frequency','w_grid_tie','SampleTime','0', ...
    'Position',[40 250 130 280]);
add_block('simulink/Sources/Sine Wave',[model_name '/Unit Sine'], ...
    'Amplitude','1','Frequency','w_grid_tie','SampleTime','0', ...
    'Position',[40 40 130 70]);
add_block('simulink/Sources/Step',[model_name '/Injection Step'], ...
    'Time','t_injection','Before','m_sync','After','m_test', ...
    'Position',[40 105 130 135]);
add_block('simulink/Math Operations/Product',[model_name '/Modulated Reference'], ...
    'Position',[180 55 225 105]);
add_block('simulink/Sources/Repeating Sequence',[model_name '/Triangle Carrier'], ...
    'rep_seq_t','carrier_time_grid','rep_seq_y','carrier_values_grid', ...
    'Position',[175 155 270 190]);
add_block('simulink/Math Operations/Gain',[model_name '/Negative Reference'], ...
    'Gain','-1','Position',[270 90 315 120]);
add_block('simulink/Logic and Bit Operations/Relational Operator',[model_name '/Leg A'], ...
    'Operator','>=','Position',[355 45 405 75]);
add_block('simulink/Logic and Bit Operations/Relational Operator',[model_name '/Leg B'], ...
    'Operator','>=','Position',[355 120 405 150]);
add_block('simulink/Signal Attributes/Data Type Conversion',[model_name '/Gate A double'], ...
    'OutDataTypeStr','double','Position',[445 45 485 75]);
add_block('simulink/Signal Attributes/Data Type Conversion',[model_name '/Gate B double'], ...
    'OutDataTypeStr','double','Position',[445 120 485 150]);
add_block('simulink/Math Operations/Sum',[model_name '/Bridge State'], ...
    'Inputs','+-','Position',[525 65 555 130]);
add_block('simulink/Math Operations/Gain',[model_name '/Bridge Voltage'], ...
    'Gain','Vdc_grid','Position',[595 82 680 112]);

add_block('simulink/Sources/Step',[model_name '/PCC Breaker'], ...
    'Time','t_breaker','Before','0','After','1','Position',[600 225 680 255]);

% Discrete LCL state update. Breaker-open operation forces grid current to zero.
plant = [model_name '/LCL and Grid Plant'];
add_block('simulink/User-Defined Functions/MATLAB Function',plant, ...
    'Position',[760 80 965 225]);
rt = sfroot;
chart = rt.find('-isa','Stateflow.EMChart','Path',plant);
chart.Script = sprintf([ ...
    'function [i1,i_grid,v_pcc,v_cap] = step_lcl(v_inv,v_grid,breaker)\n' ...
    '%%#codegen\n' ...
    'persistent x_i1 x_ig x_vc\n' ...
    'if isempty(x_i1); x_i1=0; x_ig=0; x_vc=0; end\n' ...
    'Ts=%.17g; L1=%.17g; R1=%.17g; C=%.17g; Rd=%.17g; L2=%.17g; R2=%.17g;\n' ...
    'if breaker < 0.5; x_ig=0; end\n' ...
    'i_cap=x_i1-x_ig; v_node=x_vc+Rd*i_cap;\n' ...
    'di1=(v_inv-R1*x_i1-v_node)/L1;\n' ...
    'dvc=i_cap/C;\n' ...
    'if breaker >= 0.5; dig=(v_node-R2*x_ig-v_grid)/L2; else; dig=0; end\n' ...
    'x_i1=x_i1+Ts*di1; x_vc=x_vc+Ts*dvc;\n' ...
    'if breaker >= 0.5; x_ig=x_ig+Ts*dig; else; x_ig=0; end\n' ...
    'i1=x_i1; i_grid=x_ig; v_cap=x_vc; v_pcc=x_vc+Rd*(x_i1-x_ig);\n' ...
    'end\n'],T_step_grid,L1_lcl,R1_lcl,C_lcl,Rd_lcl,L2_total,R2_total);

names = {'v_inv','v_grid','breaker','i1','i_grid','v_pcc','v_cap','m_cmd'};
positions = [705 30; 705 275; 705 325; 1010 50; 1010 95; 1010 140; 1010 185; 150 15];
for k=1:numel(names)
    add_block('simulink/Sinks/To Workspace',[model_name '/log_' names{k}], ...
        'VariableName',names{k},'SaveFormat','Timeseries', ...
        'Position',[positions(k,1) positions(k,2) positions(k,1)+80 positions(k,2)+25]);
end

add_line(model_name,'Unit Sine/1','Modulated Reference/1');
add_line(model_name,'Injection Step/1','Modulated Reference/2');
add_line(model_name,'Injection Step/1','log_m_cmd/1');
add_line(model_name,'Modulated Reference/1','Leg A/1');
add_line(model_name,'Modulated Reference/1','Negative Reference/1');
add_line(model_name,'Negative Reference/1','Leg B/1');
add_line(model_name,'Triangle Carrier/1','Leg A/2');
add_line(model_name,'Triangle Carrier/1','Leg B/2');
add_line(model_name,'Leg A/1','Gate A double/1');
add_line(model_name,'Leg B/1','Gate B double/1');
add_line(model_name,'Gate A double/1','Bridge State/1');
add_line(model_name,'Gate B double/1','Bridge State/2');
add_line(model_name,'Bridge State/1','Bridge Voltage/1');
add_line(model_name,'Bridge Voltage/1','LCL and Grid Plant/1');
add_line(model_name,'Grid Voltage/1','LCL and Grid Plant/2');
add_line(model_name,'PCC Breaker/1','LCL and Grid Plant/3');
add_line(model_name,'Bridge Voltage/1','log_v_inv/1');
add_line(model_name,'Grid Voltage/1','log_v_grid/1');
add_line(model_name,'PCC Breaker/1','log_breaker/1');
add_line(model_name,'LCL and Grid Plant/1','log_i1/1');
add_line(model_name,'LCL and Grid Plant/2','log_i_grid/1');
add_line(model_name,'LCL and Grid Plant/3','log_v_pcc/1');
add_line(model_name,'LCL and Grid Plant/4','log_v_cap/1');

Simulink.BlockDiagram.arrangeSystem(model_name);
save_system(model_name);
fprintf('Model saved: %s.slx\n',model_name);
end

