function build_grid_following_model()
%% Build switching-level grid-following inverter with PLL and PR current loop.
script_dir=fileparts(mfilename('fullpath'));
cd(script_dir);
grid_following_params;
model_name='hbridge_lcl_grid_following';

if bdIsLoaded(model_name); close_system(model_name,0); end
if exist([model_name '.slx'],'file'); delete([model_name '.slx']); end
new_system(model_name);
set_param(model_name,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep','T_step_grid','StopTime','T_sim_gfl','ReturnWorkspaceOutputs','on');

add_block('simulink/Sources/Sine Wave',[model_name '/Grid Voltage'], ...
    'Amplitude','V_grid_pk','Frequency','w_grid_tie','SampleTime','0', ...
    'Position',[35 220 125 250]);
add_block('simulink/Sources/Clock',[model_name '/Time'],'Position',[35 280 65 300]);
add_block('simulink/Sources/Ramp',[model_name '/Power Ramp'], ...
    'start','t_power_start','slope','P_ref_final/t_power_ramp', ...
    'InitialOutput','0','Position',[35 70 125 100]);
add_block('simulink/Discontinuities/Saturation',[model_name '/Power Limit'], ...
    'UpperLimit','P_ref_final','LowerLimit','0','Position',[165 70 225 100]);
add_block('simulink/Discrete/Zero-Order Hold',[model_name '/Power Command Sample'], ...
    'SampleTime','T_control_gfl','Position',[245 70 285 100]);
add_block('simulink/Discrete/Zero-Order Hold',[model_name '/Grid Voltage ADC'], ...
    'SampleTime','T_control_gfl','Position',[165 220 205 250]);
add_block('simulink/Sources/Step',[model_name '/Reactive Power Step'], ...
    'Time','t_q_step','Before','0','After','Q_ref_test','Position',[35 125 125 155]);
add_block('simulink/Discrete/Zero-Order Hold',[model_name '/Reactive Command Sample'], ...
    'SampleTime','T_control_gfl','Position',[165 125 205 155]);

controller=[model_name '/PLL and PR Current Controller'];
add_block('simulink/User-Defined Functions/MATLAB Function',controller, ...
    'Position',[315 45 560 205]);
rt=sfroot; chart=rt.find('-isa','Stateflow.EMChart','Path',controller);
chart.Script=sprintf([ ...
    'function [v_ref_pu,i_ref,theta_est,f_est,locked,saturated] = control(v_grid,i_meas,p_ref,q_ref)\n' ...
    '%%#codegen\n' ...
    'persistent va vb theta omega pll_i lock_count xr1 xr2 iref_old\n' ...
    'if isempty(va); va=0; vb=0; theta=0; omega=2*pi*%.17g; pll_i=0; lock_count=0; xr1=0; xr2=0; iref_old=0; end\n' ...
    'Ts=%.17g; Vpk=%.17g; Vrms=%.17g; Vdc=%.17g;\n' ...
    '%% SOGI and normalized SRF PLL, Heun state update\n' ...
    'dva1=%.17g*omega*(v_grid-va)-omega*vb; dvb1=omega*va;\n' ...
    'va_p=va+Ts*dva1; vb_p=vb+Ts*dvb1;\n' ...
    'dva2=%.17g*omega*(v_grid-va_p)-omega*vb_p; dvb2=omega*va_p;\n' ...
    'va=va+0.5*Ts*(dva1+dva2); vb=vb+0.5*Ts*(dvb1+dvb2);\n' ...
    'amp=sqrt(va*va+vb*vb); q=(va*cos(theta)+vb*sin(theta))/max(amp,0.1*Vpk);\n' ...
    'unsat_w=2*pi*%.17g+%.17g*q+pll_i; wmin=2*pi*%.17g; wmax=2*pi*%.17g; omega=min(max(unsat_w,wmin),wmax);\n' ...
    'if (unsat_w==omega)||(unsat_w>wmax&&q<0)||(unsat_w<wmin&&q>0); pll_i=pll_i+Ts*%.17g*q; end\n' ...
    'theta=mod(theta+Ts*omega,2*pi);\n' ...
    'if amp>0.7*Vpk && abs(q)<%.17g && abs(omega/(2*pi)-%.17g)<0.2; lock_count=min(lock_count+1,%.17g); else; lock_count=0; end\n' ...
    'locked=double(lock_count>=%.17g);\n' ...
    '%% Active/reactive current command and grid-voltage feedforward\n' ...
    'theta_current=theta-%.17g*omega*Ts;\n' ...
    'i_ref=locked*(sqrt(2)/Vrms)*(p_ref*sin(theta_current)-q_ref*cos(theta_current)); di_ref=(i_ref-iref_old)/Ts; iref_old=i_ref;\n' ...
    'err=i_ref-i_meas; resonant=2*%.17g*xr2;\n' ...
    'v_ff=v_grid+%.17g*i_ref+%.17g*di_ref; v_ctrl=%.17g*err+%.17g*resonant;\n' ...
    'v_unsat=v_ff+v_ctrl; vmax=%.17g*Vdc; v_cmd=min(max(v_unsat,-vmax),vmax); saturated=double(v_cmd~=v_unsat);\n' ...
    '%% Band-limited resonant state; freeze when saturation would increase error\n' ...
    'if ~saturated || sign(err)~=sign(v_unsat-v_cmd);\n' ...
    ' dx1=xr2; dx2=err-(2*%.17g)*xr2-(2*pi*%.17g)^2*xr1;\n' ...
    ' x1p=xr1+Ts*dx1; x2p=xr2+Ts*dx2;\n' ...
    ' dx1p=x2p; dx2p=err-(2*%.17g)*x2p-(2*pi*%.17g)^2*x1p;\n' ...
    ' xr1=xr1+0.5*Ts*(dx1+dx1p); xr2=xr2+0.5*Ts*(dx2+dx2p); end\n' ...
    'v_ref_pu=v_cmd/Vdc; theta_est=theta; f_est=omega/(2*pi);\n' ...
    'end\n'],f_grid_tie,T_control_gfl,V_grid_pk,V_grid_rms,Vdc_grid, ...
    k_sogi_gfl,k_sogi_gfl,f_grid_tie,Kp_pll_gfl,f_pll_min_gfl,f_pll_max_gfl,Ki_pll_gfl, ...
    pll_lock_q_max,f_grid_tie,pll_lock_hold/T_control_gfl,pll_lock_hold/T_control_gfl,current_phase_comp_samples, ...
    wc_current,R2_total,L1_lcl+L2_total,Kp_current,Kr_current,m_gfl_max, ...
    wc_current,f_grid_tie,wc_current,f_grid_tie);

% One-sample current feedback represents ADC and computation latency.
add_block('simulink/Discrete/Unit Delay',[model_name '/Current Sample Delay'], ...
    'SampleTime','T_control_gfl','X0','0','Position',[235 155 275 185]);

% SPWM bridge.
add_block('simulink/Sources/Repeating Sequence',[model_name '/Triangle Carrier'], ...
    'rep_seq_t','carrier_time_grid','rep_seq_y','carrier_values_grid', ...
    'Position',[615 210 710 245]);
add_block('simulink/Math Operations/Gain',[model_name '/Negative Reference'], ...
    'Gain','-1','Position',[615 100 660 130]);
add_block('simulink/Logic and Bit Operations/Relational Operator',[model_name '/Leg A'], ...
    'Operator','>=','Position',[735 60 785 90]);
add_block('simulink/Logic and Bit Operations/Relational Operator',[model_name '/Leg B'], ...
    'Operator','>=','Position',[735 135 785 165]);
add_block('simulink/Signal Attributes/Data Type Conversion',[model_name '/Gate A double'], ...
    'OutDataTypeStr','double','Position',[820 60 860 90]);
add_block('simulink/Signal Attributes/Data Type Conversion',[model_name '/Gate B double'], ...
    'OutDataTypeStr','double','Position',[820 135 860 165]);
add_block('simulink/Math Operations/Sum',[model_name '/Bridge State'], ...
    'Inputs','+-','Position',[900 80 930 145]);
add_block('simulink/Math Operations/Gain',[model_name '/Bridge Voltage'], ...
    'Gain','Vdc_grid','Position',[970 98 1055 128]);

% Breaker closes on validated PLL lock; p_ref remains zero until later.
add_block('simulink/Logic and Bit Operations/Compare To Constant',[model_name '/Lock to Breaker'], ...
    'const','0.5','relop','>=','Position',[615 285 700 315]);
add_block('simulink/Signal Attributes/Data Type Conversion',[model_name '/Breaker double'], ...
    'OutDataTypeStr','double','Position',[735 285 775 315]);

plant=[model_name '/LCL and Grid Plant'];
add_block('simulink/User-Defined Functions/MATLAB Function',plant, ...
    'Position',[1130 75 1325 220]);
chart=rt.find('-isa','Stateflow.EMChart','Path',plant);
chart.Script=sprintf([ ...
    'function [i1,i_grid,v_pcc,v_cap] = step_lcl(v_inv,v_grid,breaker)\n' ...
    '%%#codegen\n' ...
    'persistent x_i1 x_ig x_vc\n' ...
    'if isempty(x_i1); x_i1=0; x_ig=0; x_vc=0; end\n' ...
    'Ts=%.17g; L1=%.17g; R1=%.17g; C=%.17g; Rd=%.17g; L2=%.17g; R2=%.17g;\n' ...
    'if breaker<0.5; x_ig=0; end; ic=x_i1-x_ig; vn=x_vc+Rd*ic;\n' ...
    'di1=(v_inv-R1*x_i1-vn)/L1; dvc=ic/C;\n' ...
    'if breaker>=0.5; dig=(vn-R2*x_ig-v_grid)/L2; else; dig=0; end\n' ...
    'x_i1=x_i1+Ts*di1; x_vc=x_vc+Ts*dvc;\n' ...
    'if breaker>=0.5; x_ig=x_ig+Ts*dig; else; x_ig=0; end\n' ...
    'i1=x_i1; i_grid=x_ig; v_cap=x_vc; v_pcc=x_vc+Rd*(x_i1-x_ig);\n' ...
    'end\n'],T_step_grid,L1_lcl,R1_lcl,C_lcl,Rd_lcl,L2_total,R2_total);

names={'p_ref','q_ref','v_ref_pu','i_ref','theta_est','f_est','locked','saturated', ...
    'v_inv','v_grid','breaker','i1','i_grid','v_pcc','v_cap'};
for k=1:numel(names)
    x0=1380+100*mod(k-1,4); y0=30+45*floor((k-1)/4);
    add_block('simulink/Sinks/To Workspace',[model_name '/log_' names{k}], ...
        'VariableName',names{k},'SaveFormat','Timeseries', ...
        'Position',[x0 y0 x0+85 y0+25]);
end

add_line(model_name,'Power Ramp/1','Power Limit/1'); add_line(model_name,'Power Limit/1','Power Command Sample/1'); add_line(model_name,'Power Command Sample/1','PLL and PR Current Controller/3'); add_line(model_name,'Power Limit/1','log_p_ref/1');
add_line(model_name,'Reactive Power Step/1','Reactive Command Sample/1'); add_line(model_name,'Reactive Command Sample/1','PLL and PR Current Controller/4'); add_line(model_name,'Reactive Power Step/1','log_q_ref/1');
add_line(model_name,'Grid Voltage/1','Grid Voltage ADC/1'); add_line(model_name,'Grid Voltage ADC/1','PLL and PR Current Controller/1'); add_line(model_name,'Grid Voltage/1','LCL and Grid Plant/2'); add_line(model_name,'Grid Voltage/1','log_v_grid/1');
add_line(model_name,'Current Sample Delay/1','PLL and PR Current Controller/2');
add_line(model_name,'PLL and PR Current Controller/1','Leg A/1'); add_line(model_name,'PLL and PR Current Controller/1','Negative Reference/1'); add_line(model_name,'PLL and PR Current Controller/1','log_v_ref_pu/1');
add_line(model_name,'Negative Reference/1','Leg B/1'); add_line(model_name,'Triangle Carrier/1','Leg A/2'); add_line(model_name,'Triangle Carrier/1','Leg B/2');
add_line(model_name,'Leg A/1','Gate A double/1'); add_line(model_name,'Leg B/1','Gate B double/1'); add_line(model_name,'Gate A double/1','Bridge State/1'); add_line(model_name,'Gate B double/1','Bridge State/2'); add_line(model_name,'Bridge State/1','Bridge Voltage/1');
add_line(model_name,'PLL and PR Current Controller/5','Lock to Breaker/1'); add_line(model_name,'Lock to Breaker/1','Breaker double/1'); add_line(model_name,'Breaker double/1','LCL and Grid Plant/3'); add_line(model_name,'Breaker double/1','log_breaker/1');
add_line(model_name,'Bridge Voltage/1','LCL and Grid Plant/1'); add_line(model_name,'Bridge Voltage/1','log_v_inv/1');
add_line(model_name,'LCL and Grid Plant/2','Current Sample Delay/1');
for port=2:6
    add_line(model_name,sprintf('PLL and PR Current Controller/%d',port),['log_' names{port+2} '/1']);
end
for port=1:4
    add_line(model_name,sprintf('LCL and Grid Plant/%d',port),['log_' names{port+11} '/1']);
end

Simulink.BlockDiagram.arrangeSystem(model_name);
save_system(model_name);
fprintf('Model saved: %s.slx\n',model_name);
end
